version: '2'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    mem_limit: 512M
    volumes:
      - /docker/config/hass:/config
    environment:
      - TZ=Europe/Berlin
      - PUID=1002
      - PGID=1002
      - GIDLIST=1002
    restart: always
    network_mode: host
