version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    
    network_mode: "host"
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
      #- "67:67/udp"
      #  - "8080:80/tcp"
      #- "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      ServerIP: "192.168.188.220"
      #DNS1: "8.8.8.8"
      #DNS2: "8.8.4.4"
      DNS1: "192.168.188.220#5053"
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
       - '/docker/config/pihole/etc-pihole/:/etc/pihole/'
       - '/docker/config/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
       - '/docker/config/pihole/etc-hosts:/etc/hosts'
    # run `touch ./var-log/pihole.log` first unless you like errors
    # - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
