version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    #restart: always
    ports:
      - "3000:3000"
    networks:
      - web
      - default
    volumes:
      - /docker/config/grafana/data:/var/lib/grafana
      - /docker/config/grafana/grafana.ini:/etc/grafana/grafana.ini:rw
    environment:
      - PUID=1002
      - PGID=1002
      - GIDLIST=1002
      - TZ=Europe/Berlin
    expose:
      - "3000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - traefik.http.routers.grafana.rule=Host(`grafana.eth0.zone`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=le
      - traefik.http.routers.grafana.middlewares=grafana@docker
      - "traefik.http.middlewares.grafana.ipwhitelist.sourcerange=192.168.188.0/24, 10.88.88.0/24"
      - traefik.http.services.grafana.loadbalancer.server.port=3000

networks:
  web:
    external: true
