version: "3"
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest

    #network_mode: "host"
    ports:
      - "8080:80/tcp"
    environment:
      - PUID=1002
      - PGID=1002
      - GIDLIST=1002
      - TZ=Europe/Berlin
    volumes:
       - '/docker/config/adguard/workdir:/opt/adguardhome/work'
       - '/docker/config/adguard/conf:/opt/adguardhome/conf'
    networks:
      - web
      - default
        #restart: always
    expose:
      - "8080"
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - traefik.http.routers.adguard.rule=Host(`adguard.eth0.zone`)
      - traefik.http.routers.adguard.tls=true
      - traefik.http.routers.adguard.tls.certresolver=le
      - traefik.http.routers.adguard.middlewares=adguard@docker
      - "traefik.http.middlewares.adguard.ipwhitelist.sourcerange=192.168.188.0/24, 10.88.88.0/24"
      - traefik.http.services.adguard.loadbalancer.server.port=80

networks:
  web:
    external: true
