version: '3'
services:
  share:
    image: nginx:latest
    container_name: share
    volumes:
      - /ssd/media/series/zerozerozero:/srv
      - /docker/config/share/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 9999:80        
    networks:
      - web
      - default
    expose:
      - "9999"
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.routers.share.entrypoints=websecure"
      - traefik.http.routers.share.rule=Host(`share.eth0.zone`)
      - traefik.http.routers.share.tls=true
      - traefik.http.routers.share.tls.certresolver=le
      - traefik.http.routers.share.middlewares=share@docker
      - "traefik.http.middlewares.share.ipwhitelist.sourcerange=0.0.0.0/0"
      - traefik.http.services.share.loadbalancer.server.port=80

networks:
  web:
    external: true
