version: '3'
services:
  hexo:
    image: sunchase/hexo
    container_name: hexo
    volumes:
      - /docker/config/hexo:/app
    restart: always
    ports:
      - 4000:4000        
    networks:
      - web
      - default
    environment:
      - PUID=1002
      - PGID=1002
    expose:
      - "4000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.routers.hexo.entrypoints=websecure"
      - traefik.http.routers.hexo.rule=Host(`blog.eth0.zone`)
      - traefik.http.routers.hexo.tls=true
      - traefik.http.routers.hexo.tls.certresolver=le
      - traefik.http.routers.hexo.middlewares=hexo@docker
      - "traefik.http.middlewares.hexo.ipwhitelist.sourcerange=192.168.188.0/24, 10.88.88.0/24"
      - traefik.http.services.hexo.loadbalancer.server.port=4000

networks:
  web:
    external: true
